services:
  mysql:
    image: mysql:latest
    container_name: mysql-container-ecommerce
    restart: always
    environment:
      MYSQL_DATABASE: enterprise_modelling
      MYSQL_USER: sherie
      MYSQL_ROOT_PASSWORD: Password123@@
      MYSQL_PASSWORD: Password123@@
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - internal_network

  gateway-service:
    image: ecommerce/gateway-service:1.0.0
    container_name: gateway-container-ecommerce
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - internal_network

  eureka-service:
    image: ecommerce/eureka-service:1.0.0
    container_name: eureka-container-ecommerce
    ports:
      - "8761:8761"
    depends_on:
      - mysql
    networks:
      - internal_network

  product-service:
    image: ecommerce/product-service:1.0.2
    container_name: product-container-ecommerce
    depends_on:
      - mysql
    networks:
      - internal_network

  admin-service:
    image: ecommerce/admin-service:1.0.0
    container_name: admin-container-ecommerce
    depends_on:
      - mysql
    networks:
      - internal_network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3308/enterprise_modelling
      SPRING_DATASOURCE_USERNAME: sherie
      SPRING_DATASOURCE_PASSWORD: Password123@@

  order-service:
    image: ecommerce/order-service:1.0.0
    container_name: order-container-ecommerce
    depends_on:
      - mysql
    networks:
      - internal_network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3308/enterprise_modelling
      SPRING_DATASOURCE_USERNAME: sherie
      SPRING_DATASOURCE_PASSWORD: Password123@@

  image-service:
    image: ecommerce/image-service:1.0.0
    container_name: image-container-ecommerce
    depends_on:
      - mysql
    networks:
      - internal_network

networks:
  internal_network:
    external: false
    name: sherie-network


volumes:
  mysql-data: